import React from 'react'
import { createRoot } from 'react-dom/client'
import { SorbProvider, PreviewBanner } from '@sorb/leaf'
import { sorbConfig } from './src/sorbConfig'
import { App } from './src/App'

// The committed CSS custom properties the app reads (--color-*, --button-*, …).
// Generated by `npm run tokens`; a Sorb preview swaps these vars at runtime.
import './src/tokens/generated/variables.css'

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <SorbProvider config={sorbConfig}>
      <App />

      {/* Bottom banner whenever a preview is active; renders nothing in production. */}
      <PreviewBanner />
    </SorbProvider>
  </React.StrictMode>,
)
