import React from 'react'
import { createRoot } from 'react-dom/client'
import { SorbProvider, PreviewBanner } from '@sorb/leaf'
import { BootstrapStyledProvider } from '@metatoy/bootstrap-styled'
import { sorbConfig } from './src/sorbConfig'
import { sorbBsTheme } from './src/sorbBsTheme'
import { App } from './src/App'

// The committed CSS custom properties the app reads (--color-*, --bs-*, …).
// Generated by `npm run tokens`; a Sorb preview swaps these vars at runtime.
import './src/tokens/generated/variables.css'

// Provider stack (GFP RC1 Part 3 · §C.2):
//   SorbProvider            @sorb/leaf — preview/verify context (writes pushed
//                           tokens as inline --bs-* on <html> during a preview)
//     BootstrapStyledProvider   emits the Jane's Jeans theme as --bs-* on :root
//       App (BrowserRouter → SiteLayout → Routes)
//   PreviewBanner           bottom banner while a preview is active
//
// Because the committed brand IS the --bs-* set, leaf's inline override wins by
// specificity → one bs-* preview push re-skins the whole shell + components live.
createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <SorbProvider config={sorbConfig}>
      <BootstrapStyledProvider theme={sorbBsTheme}>
        <App />
      </BootstrapStyledProvider>

      {/* Bottom banner whenever a preview is active; renders nothing in production. */}
      <PreviewBanner />
    </SorbProvider>
  </React.StrictMode>,
)
