import { tokens } from './tokens/generated/tokens'

// One leaf SorbConfig shared by the running app (main.jsx) AND every Storybook
// story (.storybook/preview.jsx) — token behaviour is identical in both. The
// committed `tokens` set is generated by `npm run tokens` (Style Dictionary);
// previews override it live via the bridge.
//
// Local dev talks to `sorb dev` on localhost (no auth). The HOSTED demo build
// talks to Sorb Cloud's bridge and must send a read-only publishable key. All of
// that is env-driven — nothing is hardcoded here (Plugin-UX U4):
//
//   VITE_SORB_ORIGIN       bridge origin (default http://localhost:7777)
//   VITE_SORB_KEY          read-only publishable key (sorb_pk_…) — hosted only
//   VITE_SORB_PREVIEW      set to `on` to force-enable preview in a prod build
//   VITE_SORB_DEMO_ORIGIN  this demo app's own deployed origin (extra allowlist entry)

const env = import.meta.env

// Where the bridge is. `sorb dev` on localhost by default; the hosted bridge for
// the deployed demo (VITE_SORB_ORIGIN=https://bridge.sorbcloud.com).
const origin = env.VITE_SORB_ORIGIN ?? 'http://localhost:7777'

// Read-only publishable bearer key for the hosted bridge. Undefined for local
// dev → the SDK sends no Authorization header (localhost path unchanged).
const key = env.VITE_SORB_KEY || undefined

// Preview used to be gated purely on `MODE !== 'production'`, which turned it OFF
// in every prod build — including the hosted demo, which NEEDS it. Now it is
// explicit: on when the deploy opts in (VITE_SORB_PREVIEW=on) or supplies a key,
// and still on for local dev. A bare prod build with none of these set keeps
// preview off (safe default).
const previewEnabled =
  env.VITE_SORB_PREVIEW === 'on' || Boolean(key) || env.MODE !== 'production'

// The leaf previewGuard only trusts a non-localhost bridge origin if it is on the
// allowlist. Feed it the hosted bridge origin plus this demo's own origin (both
// env-driven; localhost/empty entries are dropped since they're trusted anyway).
const isLocal = (o) => !o || /^https?:\/\/(localhost|127\.0\.0\.1|\[?::1\]?)(:|\/|$)/.test(o)
const allowedOrigins = [origin, env.VITE_SORB_DEMO_ORIGIN].filter((o) => !isLocal(o))

/** @type {import('@sorb/leaf').SorbConfig} */
export const sorbConfig = {
  namespace: 'sorb-demo',
  tokens,
  preview: {
    enabled: previewEnabled,
    origin,
    // Bearer key for the hosted bridge; omitted (undefined) for local dev.
    key,
    // Extra trusted bridge origins (hosted bridge + demo origin); empty for local dev.
    allowedOrigins,
    pollInterval: 1500,
  },
}
