import { tokens } from './tokens/generated/tokens'

// One leaf SorbConfig shared by the running app (main.jsx) AND every Storybook
// story (.storybook/preview.jsx) — token behaviour is identical in both. The
// committed `tokens` set is generated by `npm run tokens` (Style Dictionary);
// previews override it live via the local bridge.

/** @type {import('@sorb/leaf').SorbConfig} */
export const sorbConfig = {
  namespace: 'sorb-demo',
  tokens,
  preview: {
    // Preview is dev-only; production tree-shakes this branch off.
    enabled: import.meta.env.MODE !== 'production',
    // Where `sorb dev` is running. Override with VITE_SORB_ORIGIN for staging.
    origin: import.meta.env.VITE_SORB_ORIGIN ?? 'http://localhost:7777',
    pollInterval: 1500,
  },
}
